#!/usr/bin/env python3
"""EnergyBridge interactive agent loop — human-in-the-loop mode.

Runs the identical 3-day EnergyPlus + VPP co-simulation as run_persona_json.py,
but replaces the LLM-simulated user with real human terminal input:

  - Before each VPP event (18:00-19:00, Days 1-3):
      Three strategy options (A = comfort / B = balanced / C = savings) are
      generated by the LLM and displayed.  You choose one, or type free text.

  - After each VPP event ends:
      The agent's outcome (setpoint, indoor temp, energy) is shown.
      You rate your satisfaction (1-5) and leave an optional comment.

Everything else is identical to single-persona mode:
  EnergyPlus physics, VPP grid-side demand agent, AC thermostat agent,
  appliance scheduling (washer / dishwasher / dryer / water heater / EV).

Output goes to benchmark_results/human_<YYYYMMDD_HHMMSS>/
  run_summary.txt        ← human-readable summary (check this first)
  benchmark_result.json  ← raw metrics

Usage
-----
    cd experiments/benchmark
    conda activate energybridge
    python3 run_agent_loop.py
    python3 run_agent_loop.py --city Tianjin
    python3 run_agent_loop.py --output /tmp/my_run
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path

_BENCH_DIR    = Path(__file__).resolve().parent.parent / "experiments" / "benchmark"
_PROJECT_ROOT = Path(__file__).resolve().parent.parent
from dotenv import load_dotenv
load_dotenv(_PROJECT_ROOT / ".env")

for p in (str(_PROJECT_ROOT), str(_BENCH_DIR)):
    if p not in sys.path:
        sys.path.insert(0, p)

import family_runner as fr
from run_persona_json import _write_run_summary

# ---------------------------------------------------------------------------
# Default appliance config for human player (all devices present)
# ---------------------------------------------------------------------------
_DEFAULT_APPLIANCES = {
    "washer":       {"present": True,  "preferred_start_h": 8.0,  "preferred_end_h": 10.0},
    "dishwasher":   {"present": True,  "preferred_start_h": 20.0, "preferred_end_h": 22.0},
    "dryer":        {"present": False},
    "water_heater": {"present": True,  "bath_hour": 21.0, "preheat_lead_h": 1.0},
    "ev":           {"present": False},
    "ac": {
        "setpoint_comfort": 25.0,
        "setpoint_vpp_min": 25.5,
        "setpoint_vpp_max": 27.5,
    },
}

# Minimal persona dict used only for run_summary formatting (not for LLM roleplay)
def _human_persona(city: str) -> dict:
    return {
        "id": f"human_{datetime.now().strftime('%Y%m%d_%H%M%S')}",
        "display_name": "Human Player",
        "summary": "A real household user making their own VPP decisions.",
        "preferences": {
            "scoring_weights": {"comfort": 0.4, "energy": 0.3, "vpp": 0.3},
            "comfort_priority": 0.4,
        },
        "appliances": _DEFAULT_APPLIANCES,
        "llm_prompts": {
            "system_prompt": (
                "I am a real household user. I will make my own decisions "
                "about VPP events — please show me my options."
            ),
        },
        "city": city,
    }


def main() -> None:
    parser = argparse.ArgumentParser(
        description="EnergyBridge interactive agent loop (human-in-the-loop)."
    )
    parser.add_argument("--city", "-c", default="Tianjin",
                        help="City for EPW weather file (default: Tianjin)")
    parser.add_argument("--output", "-o", default=None,
                        help="Override output directory.")
    parser.add_argument("--verbose", "-v", action="store_true")
    args = parser.parse_args()

    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_dir = (
        Path(args.output) if args.output
        else _PROJECT_ROOT / "benchmark_results" / f"human_{ts}"
    )

    persona = _human_persona(args.city)

    print("=" * 62)
    print("  EnergyBridge — Interactive Agent Loop (Human Mode)")
    print("=" * 62)
    print(f"  City       : {args.city}")
    print(f"  Output     : {output_dir}")
    print()
    print("  You will be prompted 3 times (before each VPP event) to choose")
    print("  a strategy, and 3 times (after each event) to rate the result.")
    print("  The AC + appliance agent acts autonomously between prompts.")
    print("=" * 62)
    print()

    print(f"  OUTPUT  : {output_dir}")

    result = fr.run_family_agent(
        user_pref=(
            "I am a real household user. Present me with strategy options "
            "before each VPP event so I can decide."
        ),
        appliance_config=_DEFAULT_APPLIANCES,
        output_dir=output_dir,
        weather_label=args.city,
        verbose=args.verbose,
        human_mode=True,       # ← activates terminal input for both preference
                               #   selection and post-event satisfaction scoring
    )

    output_dir.mkdir(parents=True, exist_ok=True)
    json_path = output_dir / "benchmark_result.json"
    json_path.write_text(
        json.dumps(result._asdict() if hasattr(result, "_asdict") else vars(result),
                   indent=2, ensure_ascii=False, default=str),
        encoding="utf-8",
    )
    print(f"\n[Saved] benchmark_result.json → {json_path}")

    txt_path = _write_run_summary(result, persona, args.city, output_dir)
    print(f"[Saved] run_summary.txt        → {txt_path}")
    print()
    print("Done. Check run_summary.txt for the full event log.")


if __name__ == "__main__":
    main()
