#!/usr/bin/env python3
"""Reproduce the public human role-play analysis from deidentified outcomes."""

from __future__ import annotations

import argparse
import csv
import json
import math
from collections import defaultdict
from pathlib import Path
from typing import Any, Iterable

import numpy as np

RELEASE_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = RELEASE_ROOT / "data"
METHODS = ("MPC", "HEMA", "EnergyBridge")
CONTRASTS = (
    ("EnergyBridge", "HEMA"),
    ("EnergyBridge", "MPC"),
    ("HEMA", "MPC"),
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--bootstrap-replicates", type=int, default=10_000)
    parser.add_argument("--bootstrap-seed", type=int, default=1)
    parser.add_argument(
        "--llm-counts",
        type=Path,
        help=(
            "Optional CSV generated by a new evaluator run. Required columns: "
            "method,llm_accepted,llm_trials. No historical LLM result is "
            "bundled with the release."
        ),
    )
    return parser.parse_args()


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def write_csv(
    path: Path,
    rows: Iterable[dict[str, Any]],
    fieldnames: list[str],
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


def wilson(successes: int, total: int) -> tuple[float, float]:
    z = 1.959963984540054
    p = successes / total
    denominator = 1.0 + z * z / total
    center = (p + z * z / (2.0 * total)) / denominator
    margin = (
        z
        * math.sqrt(p * (1.0 - p) / total + z * z / (4.0 * total * total))
        / denominator
    )
    return center - margin, center + margin


def exact_mcnemar(left_only: int, right_only: int) -> float:
    discordant = left_only + right_only
    if discordant == 0:
        return 1.0
    tail = min(left_only, right_only)
    probability = sum(math.comb(discordant, k) for k in range(tail + 1))
    return min(1.0, 2.0 * probability / (2**discordant))


def holm_adjust(raw: list[float]) -> list[float]:
    order = sorted(range(len(raw)), key=raw.__getitem__)
    adjusted = [0.0] * len(raw)
    running_max = 0.0
    count = len(raw)
    for rank, index in enumerate(order):
        candidate = min(1.0, raw[index] * (count - rank))
        running_max = max(running_max, candidate)
        adjusted[index] = running_max
    return adjusted


def bernoulli_jsd(p: float, q: float) -> float:
    def kl(a: float, b: float) -> float:
        terms = []
        for x, y in ((a, b), (1.0 - a, 1.0 - b)):
            terms.append(0.0 if x == 0.0 else x * math.log(x / y))
        return sum(terms)

    midpoint = 0.5 * (p + q)
    return 0.5 * kl(p, midpoint) + 0.5 * kl(q, midpoint)


def bootstrap_mean_ci(
    values: np.ndarray,
    *,
    replicates: int,
    seed: int,
) -> tuple[float, float]:
    rng = np.random.default_rng(seed)
    samples = np.empty(replicates, dtype=float)
    for index in range(replicates):
        samples[index] = rng.choice(values, size=len(values), replace=True).mean()
    low, high = np.quantile(samples, [0.025, 0.975])
    return float(low), float(high)


def grouped_rows(
    responses: list[dict[str, str]],
) -> list[tuple[str, list[dict[str, str]]]]:
    personas = list(
        dict.fromkeys(row["persona"] for row in responses)
    )
    return [("All", responses)] + [
        (persona, [row for row in responses if row["persona"] == persona])
        for persona in personas
    ]


def age_band_summary(
    participants: list[dict[str, str]],
) -> list[dict[str, Any]]:
    counts: dict[tuple[str, str], int] = defaultdict(int)
    for row in participants:
        counts[(row["persona"], row["age_band"])] += 1
    return [
        {
            "persona": persona,
            "age_band": age_band,
            "participants": count,
        }
        for (persona, age_band), count in sorted(counts.items())
    ]


def acceptance_summary(
    responses: list[dict[str, str]],
) -> list[dict[str, Any]]:
    output: list[dict[str, Any]] = []
    for persona, rows in grouped_rows(responses):
        for method in METHODS:
            values = [
                int(row["acceptance"])
                for row in rows
                if row["method"] == method
            ]
            accepted = sum(values)
            low, high = wilson(accepted, len(values))
            output.append(
                {
                    "persona": persona,
                    "method": method,
                    "n": len(values),
                    "accepted": accepted,
                    "acceptance_rate": round(accepted / len(values), 6),
                    "ci95_low": round(low, 6),
                    "ci95_high": round(high, 6),
                }
            )
    return output


def satisfaction_summary(
    responses: list[dict[str, str]],
    *,
    replicates: int,
    seed: int,
) -> list[dict[str, Any]]:
    output: list[dict[str, Any]] = []
    for persona, rows in grouped_rows(responses):
        for method in METHODS:
            values = np.asarray(
                [
                    float(row["satisfaction_score"])
                    for row in rows
                    if row["method"] == method
                ],
                dtype=float,
            )
            low, high = bootstrap_mean_ci(
                values,
                replicates=replicates,
                seed=seed,
            )
            output.append(
                {
                    "persona": persona,
                    "method": method,
                    "n": len(values),
                    "mean_satisfaction": round(float(values.mean()), 4),
                    "median_satisfaction": round(float(np.median(values)), 4),
                    "ci95_low": round(low, 4),
                    "ci95_high": round(high, 4),
                }
            )
    return output


def paired_acceptance(
    responses: list[dict[str, str]],
    *,
    replicates: int,
    seed: int,
) -> list[dict[str, Any]]:
    output: list[dict[str, Any]] = []
    for persona, rows in grouped_rows(responses):
        by_participant: dict[str, dict[str, int]] = defaultdict(dict)
        for row in rows:
            by_participant[row["participant_id"]][row["method"]] = int(
                row["acceptance"]
            )

        persona_rows: list[dict[str, Any]] = []
        raw_p_values: list[float] = []
        for left, right in CONTRASTS:
            differences = np.asarray(
                [
                    methods[left] - methods[right]
                    for methods in by_participant.values()
                ],
                dtype=float,
            )
            left_only = int(np.sum(differences == 1))
            right_only = int(np.sum(differences == -1))
            low, high = bootstrap_mean_ci(
                differences,
                replicates=replicates,
                seed=seed,
            )
            raw_p = exact_mcnemar(left_only, right_only)
            raw_p_values.append(raw_p)
            persona_rows.append(
                {
                    "persona": persona,
                    "contrast": f"{left} - {right}",
                    "n_pairs": len(differences),
                    "risk_difference": round(float(differences.mean()), 6),
                    "ci95_low": round(low, 6),
                    "ci95_high": round(high, 6),
                    "left_accept_right_reject": left_only,
                    "left_reject_right_accept": right_only,
                    "mcnemar_p_raw": raw_p,
                }
            )
        adjusted = holm_adjust(raw_p_values)
        for row, adjusted_p in zip(persona_rows, adjusted):
            row["mcnemar_p_holm_within_persona"] = adjusted_p
        output.extend(persona_rows)
    return output


def cochran_q_summary(
    responses: list[dict[str, str]],
) -> list[dict[str, Any]]:
    output: list[dict[str, Any]] = []
    for persona, rows in grouped_rows(responses):
        by_participant: dict[str, dict[str, int]] = defaultdict(dict)
        for row in rows:
            by_participant[row["participant_id"]][row["method"]] = int(
                row["acceptance"]
            )
        matrix = np.asarray(
            [[methods[method] for method in METHODS] for methods in by_participant.values()],
            dtype=float,
        )
        n, method_count = matrix.shape
        column_sums = matrix.sum(axis=0)
        row_sums = matrix.sum(axis=1)
        grand_total = float(column_sums.sum())
        numerator = method_count * (method_count - 1) * (
            float(np.square(column_sums).sum()) - grand_total**2 / method_count
        )
        denominator = method_count * grand_total - float(np.square(row_sums).sum())
        statistic = numerator / denominator
        degrees_of_freedom = method_count - 1
        if degrees_of_freedom != 2:
            raise ValueError("This dependency-free p-value path expects df=2")
        p_value = math.exp(-statistic / 2.0)
        output.append(
            {
                "persona": persona,
                "n_complete": n,
                "cochran_q": round(statistic, 6),
                "df": degrees_of_freedom,
                "p_value": p_value,
            }
        )
    return output


def human_llm_alignment(
    responses: list[dict[str, str]],
    llm_counts_path: Path,
) -> tuple[list[dict[str, Any]], dict[str, float]]:
    llm_counts = {
        row["method"]: row
        for row in read_csv(llm_counts_path)
    }
    if set(llm_counts) != set(METHODS):
        raise ValueError(
            f"Expected one LLM count row for each of {METHODS}; "
            f"found {sorted(llm_counts)}"
        )
    output: list[dict[str, Any]] = []
    gaps: list[float] = []
    for method in METHODS:
        values = [
            int(row["acceptance"])
            for row in responses
            if row["method"] == method
        ]
        human_accepted = sum(values)
        human_rate = human_accepted / len(values)
        llm_accepted = int(llm_counts[method]["llm_accepted"])
        llm_trials = int(llm_counts[method]["llm_trials"])
        if not 0 <= llm_accepted <= llm_trials:
            raise ValueError(f"Invalid LLM counts for {method}")
        llm_rate = llm_accepted / llm_trials
        low, high = wilson(human_accepted, len(values))
        gap = 100.0 * abs(llm_rate - human_rate)
        gaps.append(gap)
        output.append(
            {
                "method": method,
                "llm_accepted": llm_accepted,
                "llm_trials": llm_trials,
                "llm_acceptance_rate": round(llm_rate, 6),
                "human_accepted": human_accepted,
                "human_responses": len(values),
                "human_acceptance_rate": round(human_rate, 6),
                "human_ci95_low": round(low, 6),
                "human_ci95_high": round(high, 6),
                "absolute_gap_pp": round(gap, 4),
                "bernoulli_jsd": round(bernoulli_jsd(llm_rate, human_rate), 6),
            }
        )
    summary = {
        "mean_absolute_acceptance_gap_pp": round(float(np.mean(gaps)), 4),
        "mean_bernoulli_jsd": round(
            float(np.mean([row["bernoulli_jsd"] for row in output])),
            6,
        ),
    }
    return output, summary


def main() -> None:
    args = parse_args()
    if args.bootstrap_replicates <= 0:
        raise ValueError("--bootstrap-replicates must be positive")
    output_dir = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    participants = read_csv(DATA_DIR / "participants.csv")
    responses = read_csv(DATA_DIR / "responses.csv")

    ages = age_band_summary(participants)
    acceptance = acceptance_summary(responses)
    satisfaction = satisfaction_summary(
        responses,
        replicates=args.bootstrap_replicates,
        seed=args.bootstrap_seed,
    )
    paired = paired_acceptance(
        responses,
        replicates=args.bootstrap_replicates,
        seed=args.bootstrap_seed,
    )
    omnibus = cochran_q_summary(responses)

    write_csv(
        output_dir / "age_band_summary.csv",
        ages,
        list(ages[0]),
    )
    write_csv(
        output_dir / "acceptance_summary.csv",
        acceptance,
        list(acceptance[0]),
    )
    write_csv(
        output_dir / "satisfaction_summary.csv",
        satisfaction,
        list(satisfaction[0]),
    )
    write_csv(
        output_dir / "paired_acceptance_comparisons.csv",
        paired,
        list(paired[0]),
    )
    write_csv(
        output_dir / "acceptance_omnibus.csv",
        omnibus,
        list(omnibus[0]),
    )
    generated = [
        "age_band_summary.csv",
        "acceptance_summary.csv",
        "satisfaction_summary.csv",
        "paired_acceptance_comparisons.csv",
        "acceptance_omnibus.csv",
    ]
    if args.llm_counts is not None:
        alignment, alignment_summary = human_llm_alignment(
            responses,
            args.llm_counts.resolve(),
        )
        write_csv(
            output_dir / "human_llm_aggregate_alignment.csv",
            alignment,
            list(alignment[0]),
        )
        (output_dir / "human_llm_summary.json").write_text(
            json.dumps(alignment_summary, indent=2) + "\n",
            encoding="utf-8",
        )
        generated.extend(
            [
                "human_llm_aggregate_alignment.csv",
                "human_llm_summary.json",
            ]
        )

    print(json.dumps({"generated": generated}, indent=2))
    print(f"Wrote reproduced analysis to {output_dir}")


if __name__ == "__main__":
    main()
